language: common-lisp

matrix:
  include:
    - os: linux
      sudo: required
      env:
        - DEST=cg-linux
    - os: osx
      sudo: required
      env:
        - DEST=cg-osx
    - os: windows
      env:
        - DEST=cg.exe

install:
  - sh ./install-for-ci.sh

script:
  - make binary-ros

before_deploy:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then
      mv bin/cg bin/$DEST;
    fi
